# Generated by Django 3.1.7 on 2021-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForOrders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('assigned', models.IntegerField(default=-1)),
                ('delivery_time', models.ManyToManyField(to='courier_api.TimePeriod')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('orders', models.ManyToManyField(to='courier_api.ForOrders')),
                ('regions', models.ManyToManyField(to='courier_api.Region')),
                ('working_hours', models.ManyToManyField(to='courier_api.TimePeriod')),
            ],
        ),
    ]
